apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: localhost:5001/mongodb:1.0
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: mongodb-volume
  volumes:
  - name: mongodb-volume
    emptyDir:
      medium: Memory