apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: localhost:5001/mongodb:1.0
      ports:
        - containerPort: 27017
#TODO : VOLUME