apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: localhost:5001/mysql:1.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
  volumes:
  - name: mysql-volume
    emptyDir:
      medium: Memory