apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-deployment
  labels:
    app: productpage
spec:
  replicas: 5
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
        - name: productpage
          image: localhost:5001/productpage:1.0
          ports:
            - containerPort: 9080
          env:
            - name: FLOOD_FACTOR
              value: "0"
          readinessProbe:
            httpGet:
              path: /health
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - ls
            initialDelaySeconds: 10
            periodSeconds: 10