apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-deployment
  labels:
    app: ratings
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: ratings
          image: localhost:5001/ratings:1.0
          ports:
            - containerPort: 9080
          env:
            - name: SERVICE_VERSION
              value: "v2"