apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
  labels:
    app: reviews
spec:
  replicas: 5
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
        ports:
        - containerPort: 9080