
apiVersion: v1
kind: Pod
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  containers:
  - name: reviews
    image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
    ports:
    - containerPort: 9080