version: "2"
    
services:
  detail:
    build: details
    environment:
      - SERVICE_VERSION="v1"
      - ENABLE_EXTERNAL_BOOK_SERVICE="false"
    ports:
      - "1337:9080"
  productpage:
    build: productpage
    environment:
      - FLOOD_FACTOR=0
    ports:
      - "1400:9080"
  reviews:
    build: reviews/reviews-wlpcfg
    environment:
      - service_version="v1"
      - enable_ratings="false"
      - enable star_color="black"
    ports:
      - "1580:9080"
  ratings:
    build: ratings
    environment:
      - SERVICE_VERSION="v1"
    ports:
      - "1500:9080"
  mysql:
    build: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root #should be changed !
    ports:
      - "1567:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
